import { useEffect } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate, useSearchParams } from "react-router-dom";
import { schoolDateToday } from "../../lib/schoolTime";
import { PrincipalAttendancePage, PrincipalHomePage, PrincipalTimetablePage } from "../../pages/operations/PrincipalPages";
import { TeacherAttendancePage, TeacherHomePage, TeacherTimetablePage } from "../../pages/operations/TeacherPages";
import { createTimetableSlot, deleteTimetableSlot, getPrincipalHome, getPrincipalTimetable, getTeacherAttendance, getTeacherHome, saveTeacherAttendance, updateTimetableSlot, type NewTimetableSlot } from "./api";

function Loading() { return <div className="route-loader" role="status"><span className="route-loader__mark"/><span>Loading live school data…</span></div>; }
function Failure({ error }: { error: Error }) { return <main className="route-error"><h1>This workspace could not load.</h1><p>{error.message}</p><button onClick={() => location.reload()}>Try again</button></main>; }
function useDateParam() { const [params,setParams]=useSearchParams(); const date=params.get("date") ?? schoolDateToday(); return [date,(next:string)=>{ const updated=new URLSearchParams(params); updated.set("date",next); setParams(updated); }] as const; }

export function TeacherHomeRoute() { const [date,setDate]=useDateParam(); const query=useQuery({queryKey:["teacher-home",date],queryFn:()=>getTeacherHome(date)}); if(query.isPending)return <Loading/>; if(query.error)return <Failure error={query.error}/>; return <TeacherHomePage data={query.data} date={date} onDateChange={setDate}/>; }
export function TeacherTimetableRoute() { const query=useQuery({queryKey:["teacher-home","timetable"],queryFn:()=>getTeacherHome()}); if(query.isPending)return <Loading/>; if(query.error)return <Failure error={query.error}/>; return <TeacherTimetablePage data={query.data}/>; }
export function TeacherAttendanceRoute() {
  const [params,setParams]=useSearchParams(); const navigate=useNavigate(); const queryClient=useQueryClient(); const date=params.get("date") ?? schoolDateToday(); const classId=params.get("class_section_id");
  const home=useQuery({queryKey:["teacher-home",date],queryFn:()=>getTeacherHome(date),enabled:!classId});
  useEffect(()=>{ if(!classId && home.data?.classes[0]) void navigate(`/teacher/attendance?class_section_id=${home.data.classes[0].class_section_id}&date=${date}`,{replace:true}); },[classId,date,home.data,navigate]);
  const query=useQuery({queryKey:["teacher-attendance",classId,date],queryFn:()=>getTeacherAttendance(classId!,date),enabled:Boolean(classId)});
  if(!classId && home.isPending)return <Loading/>; if(!classId && home.error)return <Failure error={home.error}/>; if(!classId && home.data?.classes.length===0)return <Failure error={new Error("No assigned class register is available for this date.")}/>; if(query.isPending)return <Loading/>; if(query.error)return <Failure error={query.error}/>;
  return <TeacherAttendancePage key={`${query.data.class.id}-${date}`} data={query.data} date={date} onDateChange={(next)=>{const updated=new URLSearchParams(params);updated.set("date",next);setParams(updated);}} onSave={async(records)=>{await saveTeacherAttendance(classId!,date,records);await Promise.all([query.refetch(),queryClient.invalidateQueries({queryKey:["teacher-home"]}),queryClient.invalidateQueries({queryKey:["principal-home"]})]);}}/>;
}
export function PrincipalHomeRoute() { const [date,setDate]=useDateParam(); const query=useQuery({queryKey:["principal-home",date],queryFn:()=>getPrincipalHome(date)}); if(query.isPending)return <Loading/>; if(query.error)return <Failure error={query.error}/>; return <PrincipalHomePage data={query.data} date={date} onDateChange={setDate}/>; }
export function PrincipalAttendanceRoute() { const [params,setParams]=useSearchParams(); const queryClient=useQueryClient(); const date=params.get("date") ?? schoolDateToday(); const classId=params.get("class_section_id"); const home=useQuery({queryKey:["principal-home",date],queryFn:()=>getPrincipalHome(date),enabled:!classId}); const roster=useQuery({queryKey:["principal-register",classId,date],queryFn:()=>getTeacherAttendance(classId!,date),enabled:Boolean(classId)}); const setDate=(next:string)=>{const updated=new URLSearchParams(params);updated.set("date",next);setParams(updated);}; if(classId){if(roster.isPending)return <Loading/>;if(roster.error)return <Failure error={roster.error}/>;return <TeacherAttendancePage key={`${roster.data.class.id}-${date}`} portal="principal" data={roster.data} date={date} onDateChange={setDate} onSave={async(records)=>{await saveTeacherAttendance(classId,date,records);await Promise.all([roster.refetch(),queryClient.invalidateQueries({queryKey:["principal-home"]})]);}}/>;} if(home.isPending)return <Loading/>; if(home.error)return <Failure error={home.error}/>; return <PrincipalAttendancePage data={home.data} date={date} onDateChange={setDate}/>; }
export function PrincipalTimetableRoute() { const queryClient=useQueryClient(); const query=useQuery({queryKey:["principal-timetable"],queryFn:getPrincipalTimetable}); const refresh=async()=>{await queryClient.invalidateQueries({queryKey:["principal-timetable"]});await query.refetch();}; const create=useMutation({mutationFn:(slot:NewTimetableSlot)=>createTimetableSlot(slot)}); const update=useMutation({mutationFn:({id,slot}:{id:string;slot:NewTimetableSlot})=>updateTimetableSlot(id,slot)}); const remove=useMutation({mutationFn:deleteTimetableSlot}); if(query.isPending)return <Loading/>; if(query.error)return <Failure error={query.error}/>; return <PrincipalTimetablePage data={query.data} onCreate={async(slot)=>{await create.mutateAsync(slot);await refresh();}} onUpdate={async(id,slot)=>{await update.mutateAsync({id,slot});await refresh();}} onDelete={async(id)=>{await remove.mutateAsync(id);await refresh();}}/>; }
