# Stage deploy — runs on the self-hosted Windows runner after the build steps.
#
# Topology (one public origin, one ngrok tunnel):
#   https://<ngrok>/          mobile app        frontend/dist
#   https://<ngrok>/staff/    desktop dashboard frontend-desktop/dist
#   https://<ngrok>/api/...   API               backend/dist
#
# Secrets never live in the repo. They live on the host in
#   %USERPROFILE%\.omnischool\stage.env
# (DATABASE_URL, COOKIE_SECRET, NGROK_AUTHTOKEN, optional NGROK_DOMAIN, optional PORT).
# Windows PowerShell 5.1 compatible: no && / ?: / ?. operators.

param([string]$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path)
$ErrorActionPreference = "Stop"

$HostDir = Join-Path $env:USERPROFILE ".omnischool"
$EnvFile = Join-Path $HostDir "stage.env"
$RuntimeEnv = Join-Path $HostDir "runtime.env"
$NgrokDir = Join-Path $HostDir "ngrok"
$Ngrok = Join-Path $NgrokDir "ngrok.exe"

if (-not (Test-Path $EnvFile)) {
  throw "Missing $EnvFile. Host secrets live there: DATABASE_URL, COOKIE_SECRET, NGROK_AUTHTOKEN (and optionally NGROK_DOMAIN, PORT)."
}

# ---- read host config -------------------------------------------------------
$cfg = @{}
Get-Content $EnvFile | ForEach-Object {
  if ($_ -match '^\s*([^#=][^=]*)=(.*)$') { $cfg[$matches[1].Trim()] = $matches[2].Trim() }
}
foreach ($k in 'DATABASE_URL', 'COOKIE_SECRET') { if (-not $cfg[$k]) { throw "$k is not set in $EnvFile" } }
if (-not $cfg['NGROK_AUTHTOKEN']) { throw "NGROK_AUTHTOKEN is not set in $EnvFile. Sign in at https://dashboard.ngrok.com (GitHub login works), copy the authtoken, add it, and re-run." }
$Port = if ($cfg['PORT']) { $cfg['PORT'] } else { "8100" }

# ---- ngrok binary -----------------------------------------------------------
if (-not (Test-Path $Ngrok)) {
  Write-Host "Downloading ngrok..."
  New-Item -ItemType Directory -Force $NgrokDir | Out-Null
  $zip = Join-Path $NgrokDir "ngrok.zip"
  Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile $zip
  Expand-Archive -Path $zip -DestinationPath $NgrokDir -Force
  Remove-Item $zip -Force
}
& $Ngrok config add-authtoken $cfg['NGROK_AUTHTOKEN'] | Out-Null

# ---- tunnel first, so the API can be told its own public origin -------------
$pm2 = (Get-Command pm2 -ErrorAction SilentlyContinue)
if (-not $pm2) { throw "pm2 is not on PATH for the runner. Install with: npm install -g pm2" }

$Eco = Join-Path $HostDir "ecosystem.stage.config.cjs"
$ngrokArgs = @("http", $Port, "--log", "stdout", "--log-format", "json")
if ($cfg['NGROK_DOMAIN']) { $ngrokArgs += @("--domain", $cfg['NGROK_DOMAIN']) }
$js = @"
// Generated by deploy/stage.ps1 — do not edit by hand.
module.exports = { apps: [
  { name: "omnischool-ngrok", script: $(($Ngrok -replace '\\','/') | ConvertTo-Json), args: $($ngrokArgs | ConvertTo-Json -Compress), interpreter: "none",
    autorestart: true, restart_delay: 3000 },
  { name: "omnischool-api", script: $((Join-Path $Root "backend\dist\main.js") -replace '\\','/' | ConvertTo-Json), cwd: $((Join-Path $Root "backend") -replace '\\','/' | ConvertTo-Json),
    node_args: $("--env-file=" + ($RuntimeEnv -replace '\\','/') | ConvertTo-Json), autorestart: true, restart_delay: 3000, max_memory_restart: "512M" }
] };
"@
Set-Content -Path $Eco -Value $js -Encoding ascii
pm2 delete omnischool-ngrok 2>$null | Out-Null
pm2 start $Eco --only omnischool-ngrok | Out-Null

$Public = $null
for ($i = 0; $i -lt 40; $i++) {
  try {
    $t = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels" -TimeoutSec 3
    $https = @($t.tunnels | Where-Object { $_.public_url -like "https://*" })
    if ($https.Count -gt 0) { $Public = $https[0].public_url; break }
  } catch { }
  Start-Sleep -Seconds 1
}
if (-not $Public) {
  Write-Host "--- ngrok log ---"; pm2 logs omnischool-ngrok --nostream --lines 30 2>$null
  throw "ngrok did not expose a public URL. Check the authtoken and the log above."
}
Write-Host "Public origin: $Public"

# ---- runtime env for the API (host secrets + resolved paths + public origin) --
$managed = '^(PORT|HOST|ALLOWED_ORIGINS|PUBLIC_URL|SPA_DIST_DIR|STAFF_DIST_DIR|NGROK_AUTHTOKEN|NGROK_DOMAIN|COOKIE_SECURE|TRUST_PROXY)='
$lines = @(Get-Content $EnvFile | Where-Object { $_ -notmatch $managed -and $_.Trim() -ne "" })
$lines += "PORT=$Port"
$lines += "HOST=127.0.0.1"
$lines += "ALLOWED_ORIGINS=http://127.0.0.1:$Port,http://localhost:$Port,$Public"
$lines += "PUBLIC_URL=$Public"
$lines += "SPA_DIST_DIR=$Root\frontend\dist"
$lines += "STAFF_DIST_DIR=$Root\frontend-desktop\dist"
$lines += "COOKIE_SECURE=true"
$lines += "TRUST_PROXY=true"
Set-Content -Path $RuntimeEnv -Value $lines -Encoding ascii

# ---- migrations -------------------------------------------------------------
Push-Location (Join-Path $Root "backend")
try {
  node --env-file="$RuntimeEnv" --import tsx src/database/migrate.ts
  if ($LASTEXITCODE -ne 0) { throw "migrations failed" }
} finally { Pop-Location }

# ---- API --------------------------------------------------------------------
pm2 delete omnischool-api 2>$null | Out-Null
pm2 start $Eco --only omnischool-api | Out-Null
pm2 save | Out-Null

# ---- health -----------------------------------------------------------------
$ready = $false
for ($i = 0; $i -lt 40; $i++) {
  try {
    $r = Invoke-RestMethod -Uri "http://127.0.0.1:$Port/readyz" -TimeoutSec 3
    if ($r.status -eq "ready") { $ready = $true; break }
  } catch { }
  Start-Sleep -Seconds 1
}
if (-not $ready) { pm2 logs omnischool-api --nostream --lines 40 2>$null; throw "API did not become ready on port $Port" }

$hdr = @{ "ngrok-skip-browser-warning" = "1" }
$pub = Invoke-RestMethod -Uri "$Public/readyz" -Headers $hdr -TimeoutSec 15
$mobile = (Invoke-WebRequest -Uri "$Public/" -Headers $hdr -TimeoutSec 15 -UseBasicParsing).StatusCode
$staff = (Invoke-WebRequest -Uri "$Public/staff/" -Headers $hdr -TimeoutSec 15 -UseBasicParsing).StatusCode

Write-Host ""
Write-Host "Deployed."
Write-Host "  Mobile app        $Public/            [$mobile]"
Write-Host "  Desktop dashboard $Public/staff/       [$staff]"
Write-Host "  API               $Public/api/docs     database=$($pub.database)"
Write-Host ""
Write-Host "Free ngrok shows a one-time interstitial in browsers; API clients can send 'ngrok-skip-browser-warning: 1'."
