import { useMemo, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { AlertTriangle, ArrowRight, CalendarCheck, CheckCircle2, Clock3, LoaderCircle, Pencil, Plus, School, Trash2, UsersRound } from "lucide-react";
import type { NewTimetableSlot, PrincipalHomeResponse, PrincipalTimetableResponse } from "../../features/operations/api";
import { OperationsShell } from "./OperationsShell";

function time(value: string) {
  const [hour = "0", minute = "00"] = value.split(":");
  const numeric = Number(hour);
  return `${numeric % 12 || 12}:${minute} ${numeric >= 12 ? "PM" : "AM"}`;
}

export function PrincipalHomePage({ data, date, onDateChange }: { data: PrincipalHomeResponse; date: string; onDateChange: (date: string) => void }) {
  const coverage = data.summary.classes_total ? Math.round(data.summary.classes_submitted * 100 / data.summary.classes_total) : 0;
  return <OperationsShell portal="principal" active="home" title="School operations overview" subtitle={`${data.principal.name} • Principal workspace`}>
    <div className="operations-stack">
      <section className="operations-hero operations-hero--principal"><div><span>Live school pulse</span><h2>{data.summary.attendance_percentage}% attendance today</h2><p>Track register completion, intervene on exceptions, and protect timetable quality from one desk.</p></div><label>Date<input type="date" value={date} onChange={(event) => onDateChange(event.target.value)} /></label></section>
      <section className="operations-metrics"><article><span><UsersRound size={19}/></span><small>Students marked</small><strong>{data.summary.marked}/{data.summary.students}</strong><em>{data.summary.attending} attending</em></article><article><span><CalendarCheck size={19}/></span><small>Register coverage</small><strong>{coverage}%</strong><em>{data.summary.classes_submitted}/{data.summary.classes_total} classes submitted</em></article><article><span><AlertTriangle size={19}/></span><small>Absent today</small><strong>{data.summary.absent}</strong><em>{data.summary.late} late arrivals</em></article><article><span><School size={19}/></span><small>At-risk students</small><strong>{data.exceptions.length}</strong><em>Below class threshold</em></article></section>
      <section className="operations-panel principal-class-coverage"><header><div><span>Daily control</span><h2>Class register coverage</h2></div><Link className="operations-action-link" to={`/principal/attendance?date=${date}`}>Open attendance desk <ArrowRight size={15}/></Link></header><div className="principal-table"><div className="principal-table__head"><span>Class</span><span>Register</span><span>Attendance</span><span>Timetable</span><span/></div>{data.classes.map((item) => <article key={item.id}><span><strong>{item.name}</strong><small>{item.room_number || "Room pending"}</small></span><span><b className={`submission-chip is-${item.submission_status}`}>{item.submission_status.replace("_", " ")}</b><small>{item.marked_count}/{item.student_count} marked</small></span><span><strong>{item.attendance_percentage}%</strong><small>{item.absent_count} absent • {item.late_count} late</small></span><span><strong>{item.timetable_slots} slots</strong><small>{item.unassigned_slots ? `${item.unassigned_slots} unassigned` : "Fully assigned"}</small></span><Link className="operations-action-link" to={`/principal/attendance?class_section_id=${item.id}&date=${date}`}>Review <ArrowRight size={15}/></Link></article>)}</div></section>
      <section className="operations-panel principal-exceptions"><header><div><span>Early intervention</span><h2>Attendance exceptions</h2></div><b>Minimum 5 recorded days</b></header>{data.exceptions.length ? <div>{data.exceptions.map((student) => <article key={student.id}><span className="exception-score">{student.percentage}%</span><span><strong>{student.name}</strong><small>{student.class_name} • {student.admission_number}</small></span><span><small>School threshold</small><strong>{student.threshold}%</strong></span></article>)}</div> : <div className="operations-empty"><CheckCircle2 size={24}/><div><strong>No threshold exceptions</strong><p>Every eligible student is currently above the attendance threshold.</p></div></div>}</section>
    </div>
  </OperationsShell>;
}

export function PrincipalAttendancePage({ data, date, onDateChange }: { data: PrincipalHomeResponse; date: string; onDateChange: (date: string) => void }) {
  return <OperationsShell portal="principal" active="attendance" title="Attendance control desk" subtitle="School-wide register monitoring"><div className="operations-stack">
    <section className="attendance-register-toolbar"><label>Register date<input type="date" value={date} onChange={(event) => onDateChange(event.target.value)}/></label><span>{data.summary.classes_submitted} of {data.summary.classes_total} class registers complete</span></section>
    <section className="operations-panel principal-attendance-board"><header><div><span>All sections</span><h2>Register status and daily attendance</h2></div><b>{data.summary.attendance_percentage}% attending</b></header><div>{data.classes.map((item) => <article key={item.id}><span className="principal-class-badge">{item.grade}{item.section}</span><span><strong>{item.name}</strong><small>Room {item.room_number}</small></span><span className="coverage-meter"><i><b style={{ width: `${item.student_count ? item.marked_count * 100 / item.student_count : 0}%` }}/></i><small>{item.marked_count}/{item.student_count} marked</small></span><span><strong>{item.attendance_percentage}%</strong><small>{item.attending_count} attending</small></span><Link className="operations-action-link" to={`/principal/attendance?class_section_id=${item.id}&date=${date}`}>Open register <ArrowRight size={15}/></Link></article>)}</div></section>
  </div></OperationsShell>;
}

const initialSlot = (data: PrincipalTimetableResponse): NewTimetableSlot => ({ class_section_id: data.classes[0]?.id ?? "", subject_id: data.subjects[0]?.id ?? null, teacher_user_id: data.teachers[0]?.id ?? null, weekday: 1, period_number: 1, starts_at: "08:00", ends_at: "08:45", slot_type: "class", title: "", room: data.classes[0]?.room_number ?? "", teacher_designation: "Subject Teacher" });

export function PrincipalTimetablePage({ data, onCreate, onUpdate, onDelete }: { data: PrincipalTimetableResponse; onCreate: (slot: NewTimetableSlot) => Promise<void>; onUpdate: (id: string, slot: NewTimetableSlot) => Promise<void>; onDelete: (id: string) => Promise<void> }) {
  const [open, setOpen] = useState(false); const [editingId, setEditingId] = useState<string | null>(null); const [slot, setSlot] = useState(() => initialSlot(data)); const [state, setState] = useState<"idle"|"saving"|"saved"|"error">("idle"); const [message, setMessage] = useState("");
  const days = useMemo(() => { const map = new Map<string, PrincipalTimetableResponse["slots"]>(); for (const item of data.slots) map.set(item.weekday_label, [...(map.get(item.weekday_label) ?? []), item]); return [...map.entries()]; }, [data.slots]);
  const startNew = () => { setEditingId(null); setSlot(initialSlot(data)); setMessage(""); setOpen(true); };
  const startEdit = (item: PrincipalTimetableResponse["slots"][number]) => { setEditingId(item.id); setSlot({ class_section_id:item.class_section_id, subject_id:item.subject_id, teacher_user_id:item.teacher_user_id, weekday:item.weekday, period_number:item.period_number, starts_at:item.starts_at.slice(0,5), ends_at:item.ends_at.slice(0,5), slot_type:item.slot_type, title:item.subject_id ? "" : item.display_title, room:item.room, teacher_designation:"Subject Teacher" }); setMessage(""); setOpen(true); window.scrollTo({top:0,behavior:"smooth"}); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setState("saving"); setMessage(""); try { if(editingId) await onUpdate(editingId,slot); else await onCreate(slot); setState("saved"); setMessage(editingId ? "Period updated successfully." : "Period published successfully."); setOpen(false); setEditingId(null); } catch (error) { setState("error"); setMessage(error instanceof Error ? error.message : "The period could not be saved."); } };
  const remove = async () => { if(!editingId || !window.confirm("Remove this timetable period? This action is recorded in the audit log.")) return; setState("saving"); try { await onDelete(editingId); setState("saved"); setMessage("Period removed successfully."); setOpen(false); setEditingId(null); } catch(error) { setState("error"); setMessage(error instanceof Error ? error.message : "The period could not be removed."); } };
  return <OperationsShell portal="principal" active="timetable" title="Master timetable" subtitle="Scheduling, staffing and conflict control"><div className="operations-stack">
    <section className="operations-hero operations-hero--principal"><div><span>Published schedule</span><h2>{data.slots.length} periods across {data.classes.length} classes</h2><p>Every class, room, teacher, and time window is checked before publication.</p></div><button className="operations-primary-button" onClick={startNew}><Plus size={17}/>Add period</button></section>
    {data.conflicts.length ? <section className="operations-alert"><AlertTriangle size={20}/><div><strong>{data.conflicts.length} scheduling conflicts need attention</strong><p>Resolve overlapping room or teacher allocations before the timetable is considered final.</p></div></section> : <section className="operations-alert is-success"><CheckCircle2 size={20}/><div><strong>No scheduling conflicts</strong><p>Published teacher and room allocations do not overlap.</p></div></section>}
    {open ? <form className="operations-panel timetable-form" onSubmit={(event) => void submit(event)}><header><div><span>{editingId ? "Edit timetable period" : "New timetable period"}</span><h2>Schedule details</h2></div></header><div className="timetable-form__grid"><label>Class<select required value={slot.class_section_id} onChange={(event) => { const selected=data.classes.find((item)=>item.id===event.target.value); setSlot({...slot,class_section_id:event.target.value,room:selected?.room_number ?? slot.room}); }}>{data.classes.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Subject<select value={slot.subject_id ?? ""} onChange={(event)=>setSlot({...slot,subject_id:event.target.value || null})}><option value="">Activity / break</option>{data.subjects.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Teacher<select value={slot.teacher_user_id ?? ""} onChange={(event)=>setSlot({...slot,teacher_user_id:event.target.value || null})}><option value="">Unassigned</option>{data.teachers.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Day<select value={slot.weekday} onChange={(event)=>setSlot({...slot,weekday:Number(event.target.value)})}>{["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"].map((day,index)=><option key={day} value={index+1}>{day}</option>)}</select></label><label>Period<input type="number" min="1" max="20" value={slot.period_number} onChange={(event)=>setSlot({...slot,period_number:Number(event.target.value)})}/></label><label>Room<input required={slot.slot_type === "class"} value={slot.room} onChange={(event)=>setSlot({...slot,room:event.target.value})}/></label><label>Starts<input required type="time" value={slot.starts_at} onChange={(event)=>setSlot({...slot,starts_at:event.target.value})}/></label><label>Ends<input required type="time" value={slot.ends_at} onChange={(event)=>setSlot({...slot,ends_at:event.target.value})}/></label></div><footer><span>{editingId ? <button className="timetable-delete" type="button" onClick={()=>void remove()}><Trash2 size={16}/>Remove period</button> : <button type="button" onClick={()=>setOpen(false)}>Cancel</button>}</span><button type="submit" disabled={state==="saving"}>{state==="saving"?<LoaderCircle className="spin" size={17}/>:editingId?<Pencil size={17}/>:<Plus size={17}/>}{editingId ? "Save changes" : "Publish period"}</button></footer></form> : null}
    {message ? <p className={state === "error" ? "operations-error" : "operations-success"} role="status">{message}</p> : null}
    <section className="principal-timetable-grid">{days.map(([day, slots])=><article className="operations-panel" key={day}><header><div><span>Schedule</span><h2>{day}</h2></div><b>{slots.length} periods</b></header><div>{slots.map((item)=><section key={item.id}><span><Clock3 size={15}/>{time(item.starts_at)}–{time(item.ends_at)}</span><span><strong>{item.display_title}</strong><small>{item.class_name} • {item.teacher_name ?? "Unassigned"}</small></span><button className="principal-slot-edit" type="button" onClick={()=>startEdit(item)} aria-label={`Edit ${item.display_title} for ${item.class_name}`}><b>{item.room || "—"}</b><Pencil size={13}/></button></section>)}</div></article>)}</section>
  </div></OperationsShell>;
}
